### PR TITLE
Bug fixes and improvements

### PR DESCRIPTION
**Pull request by spacedmonkey**
Had a number of problems when installing this plugin and I thought I would fix them. The biggest ones were that I wanted to proxy the curl request. So I replaced it with the built in WordPress wp_get_remote function. I was also unable to see the panel in the admin, which I have also fixed. 

Here is a full list of changes. 
- Removed references to CURL and replaces with the built-in wp_get_remote function.
- Fixed bug where admin panel was no accessible by admin accounts.
- New filter 'disqus_rcw_recent_comment_format' for change the html markup of each comment

### CODE REVIEW

**Comment by andrewbartel** [comment]
Hey Spaced, thanks for the contribution, I'll review this weekend.

**Comment by spacedmonkey** [comment]
No problem. Glad to help :smile:

**Comment by andrewbartel** [comment]
Thanks Spaced, good stuff.  I've got some vacation coming up in about a week so I'll finally have some time to test and push out the new stuff to the svn repo.

**Comment by spacedmonkey** [comment]
Cool. It shouldn't take you that long, the biggest thing was replacing the curl with the built-in `wp_remote_get` function. I also made the html markup for each comment filterable, as I need custom html markup for my theme ( I am using bootstrap ). However this should not effect the standard usage of the plugin. :smile:

**Comment by spacedmonkey** [comment]
I hate to nag but is there any progress on putting this code onto wordpress plugin repo. I have been holding off using this plugin in production until my work was on the wordpress repo.

**Comment by andrewbartel** [comment]
Sorry for the delay, I was out of town last week and didn't want to push 1.2 out when I wasn't going to be available to answer questions or help with support.  Give me a couple days and I'll get it out to the wp.org svn repo,

**Comment by andrewbartel** [comment]
Hey spaced, I just pushed up the wp.org, let me know if you run into any issues.

**Pull request merged**
