### PR TITLE
Add transient caching

### PR DESCRIPTION
**Pull request by ghost**
Added transient caching to widget (default refresh time is 10 minutes)

### CODE REVIEW

**Comment by andrewbartel** [comment]
Thanks rkmd!  It looks like this pull request is against a few a commits ago but I'll handle the merge/rebase when I get some free time, or go ahead and do it you want.

**Comment by spacedmonkey** [comment]
@rkmd I am not sure that your code is sound. Where is the variable `$YOURDISQUS` set? According to the [get_transient](https://codex.wordpress.org/Function_Reference/get_transient) api, this should be a string, but this isn't set anywhere? This will be an empty string and will never work. You just need something like 

```
$YOURDISQUS = 'disqus_rcw'
```

@andrewbartel I wouldn't merge this until this is resolved.

**Comment by andrewbartel** [comment]
@spacedmonkey Yea, I hadn't actually reviewed the code yet since it needed a rebase before the merge would work.  The transients api is definitely the way to go for caching though I think.  @rkmd Do you want to rework this and resubmit the pull request?

**Comment by spacedmonkey** [comment]
I agree that caching should be implemented. I am currently looking to use this plugin on a high traffic site and I was having the problem that might hit the max number of api calls. Also without caching, this plugin makes a call every-time the widget is loaded, making another api call to disqus. This makes it noticeably, slower. 

Also, @rkmd, the cache time is currently set to 600 ( 10 minutes ). Could you make it filterable, so it can be overridden?

**Comment by ghost** [comment]
You all are free to modify whatever you want. I'm a rookie, lol.

**Comment by andrewbartel** [comment]
Hey @rkmd I'm going to close this, but I appreciate the contribution, I'm going to use your code as a base for implementing caching.  If you want to put together a merge against the latest commit, please feel free to re-open.

**Pull request closed without merging**
